// Coco Surf School — design-06 multipage — ENGLISH content
const CARDS = [
  { img: 'owner-lesson-deluxe.png', alt: 'A small group of surfers on the beach', title: 'Deluxe group lesson', from: 'from €52', p: 'A lesson with 2 to max 6 people per instructor: the formula between group and private to progress faster. More one-on-one time with the coach.', chips: ['Small group · max 6', '±2h total', 'Gear included'] },
  { img: 'a29fce_4b942950b2834ef2ad4e3191df3d547a.jpg', alt: 'Students learning to surf in the white water', title: 'Group lesson', from: 'from €40', p: 'A quality lesson of 7 to 8 people with one instructor. Good vibes and great company included.', chips: ['Largest group · 7–8', '±2h total', 'Gear included'] },
  { img: 'a29fce_449771ae1e2d4c52aa0fbe3159160d3b.jpg', alt: 'A surfer riding a beautiful green wave', title: 'Private lesson', from: 'from €130', p: 'A lesson just for you, as a couple, with family or friends. An instructor fully dedicated to your progression.', chips: ['Your own group · 1–7', '±2h total', 'Tailor-made'] },
  { img: 'owner-team.png', alt: 'Colleagues heading to the ocean with their boards', title: 'Companies &amp; team building', from: 'on request', p: 'A sporty day out with your colleagues! Team spirit, stress relief and smiles all round.', chips: ['On request', 'Team bonding'] },
];
export default {
  waText: 'Hello Coco Surf School, I’d love to book a surf lesson.',
  ui: {
    nav: { lessons: 'Lessons &amp; rates', coach: 'Coach', stay: 'Stay', srilanka: 'Sri Lanka', contact: 'Contact', learn: 'Learn to surf' },
    navLabel: 'Main navigation', book: 'Book now', langLabel: 'Language', menuOpen: 'Open menu',
    crumbHome: 'Home', footTagline: 'Surf school in Seignosse &amp; Hossegor. Quality over quantity — small-group lessons with Annelies.', footNav: 'Explore', langWord: 'Language',
  },
  pages: {
    home: {
      title: 'Coco Surf School — Learn to surf in Hossegor &amp; Seignosse',
      desc: 'Surf school in Seignosse &amp; Hossegor, France. Small-group lessons of max 6 people, calm and easy, board and wetsuit included.',
      jsonld: { '@context': 'https://schema.org', '@type': 'SportsActivityLocation', name: 'Coco Surf School', description: 'Surf school in Seignosse and Hossegor (Landes, France), small-group lessons of maximum 6 people.', url: 'https://www.coco-surfschool.com/en/', telephone: '+33647454265', email: 'cocobosurfschool@gmail.com', priceRange: '€40–€310', areaServed: ['Seignosse', 'Hossegor', 'Capbreton', 'Les Landes'], address: { '@type': 'PostalAddress', addressLocality: 'Seignosse', addressRegion: 'Landes', postalCode: '40510', addressCountry: 'FR' }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '5.0', reviewCount: '7' } },
      hero: { eyebrow: 'Mobile surf school · Seignosse, Hossegor &amp; Capbreton', h1: 'Learn to surf in <em>Seignosse &amp; Hossegor</em>', lead: 'Lessons, camps and coaching for beginners and advanced surfers alike — in a small group, private or group lesson. Guided by certified coaches, board and wetsuit included.', cta1: 'Book a lesson', cta2: 'See rates', cta3: 'Book a surf camp', facts: [{ b: '6', s: 'max / group' }, { b: '±2h', s: 'per lesson (1h30 in the water)' }, { b: '5 days', s: 'camp · 5 × 2h' }, { b: '€52', s: 'from, per person' }], imgAlt: 'Coco Surf School students facing the ocean at Seignosse', badge1: 'Ocean view', badge2: 'Seignosse &amp; Hossegor' },
      trust: [{ ic: '👥', b: 'Small groups', s: 'Max 6 people (8 on request)' }, { ic: '🏄‍♀️', b: 'Certified coaches', s: 'ISA &amp; FR qualified coaches' }, { ic: '🩱', b: 'Gear included', s: 'Board &amp; wetsuit provided' }, { ic: '📍', b: 'Mobile school', s: 'The best spot for your level' }],
      philosophy: { eyebrow: 'Our philosophy', title: 'A little school that takes the time to do it right', lead: 'Quality over quantity. Small groups, experienced coaches and plenty of water time — so you progress faster and have more fun.', points: [{ h: 'Quality over quantity', p: 'Maximum 6 per group (8 on request), for more coaching and faster progression.' }, { h: 'Progress in a great atmosphere', p: 'Learning to surf should feel good — good vibes guaranteed, from your first wave to your first green.' }, { h: 'The right spot, every day', p: 'A mobile school between Seignosse, Hossegor and Capbreton: we pick wherever surfs best that day.' }] },
      lessonsT: { eyebrow: 'The formulas', title: 'Choose the lesson that suits you', lead: 'All lessons last 1h30 in the water — allow ±2h in total (travel and changing included). Board and wetsuit included. Lesson hours depend on the tide, ocean conditions and your level.', cards: CARDS, more: 'See all lessons &amp; rates' },
      spots: { eyebrow: 'Where we surf', title: 'Two of the finest spots in the Landes', lead: 'A mobile school between Seignosse, Hossegor and Capbreton — we choose the best spot for your level and the conditions of the day.', hossegor: { alt: 'The surf beaches of Hossegor', h: 'Surf in Hossegor', p: 'Renowned beach breaks, a surf town and lessons for every level.' }, seignosse: { alt: 'Les Bourdaines beach in Seignosse', h: 'Surf in Seignosse', p: 'Our summer camp at Les Bourdaines — gentle waves, perfect for beginners.' } },
      reviews: { eyebrow: 'Reviews', title: 'They surfed with us', sub: '5.0 · Verified Google reviews', cta: 'View on Google' },
      coachT: { alt: 'Annelies, Coco Surf School coach, riding a wave', eyebrow: 'Your coach', title: 'Annelies, aka “Bo”', quote: '“Surfing is one of the most beautiful discoveries of my life.”', p: 'A surf instructor qualified by ISA & FR, sports teacher and lifelong athlete. After ten years travelling and surfing, Annelies settled in Seignosse to open a calm, human-sized school. Progress in a great atmosphere — good vibes guaranteed!', cta: 'Meet Annelies' },
      sriT: { alt: 'The Sri Lankan family on the south coast', eyebrow: 'Surf camp · Sri Lanka', title: 'Sri Lanka, with family', p: 'Spend the winter on the south coast, with our Sri Lankan family, 100 m from Midigama beach. Home cooking, a jungle garden and gentle waves — the real Sri Lanka.', cta: 'Discover the camp' },
      cta: { h: 'Ready to catch your first wave?', p: 'Small groups, all levels, board & wetsuit included. Write to us — we’ll be happy to reply.', b1: 'Book a lesson', b2: 'Message us on WhatsApp' },
    },
    lessons: {
      title: 'Surf lessons &amp; rates — Coco Surf School Hossegor &amp; Seignosse', desc: 'Surf lessons in the Landes: deluxe group (max 6) from €52, group from €40, private from €130. Board & wetsuit included, 1h30.', h1: 'Surf lessons', crumb: 'Lessons & rates',
      eyebrow: 'The formulas &amp; rates', h1html: 'Choose the lesson that <em>suits you</em>', lead: 'All lessons last 1h30 in the water — allow ±2h in total (travel and changing included). Board and wetsuit included. Lesson hours depend on the tide, ocean conditions and your level.', cta1: 'Book a lesson', cta2: 'Message us on WhatsApp',
      cards: CARDS, note: '<strong>Good to know —</strong> board and wetsuit are always included. Duration: 1h30 per session — allow ±2h in total (travel and changing included).',
      rates: { eyebrow: 'Rates', title: 'Clear prices, all included', lead: 'Board and wetsuit included · 1h30 per lesson · “pp” = per person.', cards: [
        { featured: true, h: 'Deluxe group', flag: 'Most popular', sub: 'One instructor for up to 6 people (min. 2).', lines: [['1 lesson', '€52 pp'], ['Little surf trip (3 lessons)', '€138 pp'], ['5-day camp (5 lessons)', '€220 pp'], ['Family discount (3 sign-ups)', '€215 pp']], incl: '2 or 4 lessons also possible · Board &amp; wetsuit included · 1h30' },
        { h: 'Group', sub: 'Larger groups — one instructor for up to 8 (min. 3 to run a class).', lines: [['1 lesson', '€40 pp'], ['Little surf trip (3 lessons)', '€115 pp'], ['5-day camp (5 lessons)', '€175 pp']], incl: '2 or 4 lessons also possible · Board &amp; wetsuit included · 1h30' },
        { h: 'Private lessons', sub: 'Board &amp; wetsuit included · 1h30 (~1h15 coaching).', lines: [['1 person', '€130 <small>Jul–Aug: €180</small>'], ['2 people', '€170 <small>Jul–Aug: €200</small>'], ['3 people', '€240 <small>Jul–Aug: €260</small>'], ['4 people', '€290'], ['5 to 7 people', '€310']], incl: 'A private instructor just for you' },
      ], extra: [{ h: 'Surf guiding', p: 'Discover other beaches of Seignosse, Hossegor or Capbreton — it takes 5–6 hours (2 surf sessions). Rates on demand.' }, { h: 'Booking &amp; payment', p: 'A 30% deposit is requested on booking. Payment by bank transfer or cash.' }] },
    },
    coach: {
      title: 'Your coach Annelies — Coco Surf School Hossegor', desc: 'Meet Annelies (“Bo”), a surf instructor qualified by ISA & FR and founder of Coco Surf School in Hossegor/Seignosse.', h1: 'Your coach', crumb: 'Coach', imgAlt: 'Annelies, coach and founder of Coco Surf School, smiling portrait', eyebrow: 'Your coach',
      quote: '“Surfing changed my life: a new world opened up! Sports and coaching are my life.”',
      body: ['Annelies is here to introduce you to surfing or help you progress! A fan of surfing and many other sports, born in Belgium where she trained at a high level in trampoline, she discovered surfing at 16 on a family holiday in Soustons.', 'After a Master in Physical Education she followed her dream and went surfing, snowboarding and working around the world: Australia, New Zealand, USA, Indonesia, Sri Lanka, Fiji, Morocco… “After my life as a competitor, it was so logical to become a sports, surf and snowboard teacher.”', 'After 10 years of travelling, the ocean called her back and she settled in Seignosse. “I had the honour of working with the Hossegor Surf Club; today I’m delighted to welcome you to my own school. Coco Surf School focuses on quality, not quantity: small-group lessons of maximum 6 people.”'],
      dipTitle: 'Diplomas &amp; certifications', diplomas: [['2000', 'Initiator Snowboard (VSSF)'], ['2003', 'Master in Physical Education, KU Leuven'], ['2003', 'Teacher degree, KU Leuven'], ['2003', 'Trainer A fitness &amp; personal trainer, VTS'], ['2006', 'Level 2 Snowboard, ASI (US)'], ['2009', 'Level 1 ISA Surf Coach &amp; Lifeguard'], ['2013', 'Carte professionnelle Éducateur Sportif Surf (FR)'], ['2020', 'International Surf Judge, ISA'], ['2021', 'PSE1 First Aid, Hossegor']], cta: 'Book a lesson with Annelies',
    },
    stay: {
      title: 'Where to stay — Accommodation near Coco Surf School, Seignosse', desc: 'Places to stay near Coco Surf School in Seignosse & Hossegor: Maison Irene, Villa & Maison de la Dune, Board & Breakfast and campsites.', h1: 'Where to stay', crumb: 'Stay',
      eyebrow: 'Where to stay', h1html: 'Places to stay right <em>next to</em> the school', lead: 'A few trusted addresses to drop your bags a stone’s throw from the ocean.',
      cards: [
        { pin: 'Seignosse · Les Bourdaines', h: 'Maison Irene', p: '8 people, 3 bedrooms + sofa bed, 2 bathrooms, large terrace with Jacuzzi. 100 m from the beach and the school. Airbnb listing available.', href: 'mailto:tudela_sire@hotmail.com', link: 'Contact Irene' },
        { pin: 'Seignosse', h: 'Villa de la Dune', p: 'A spacious holiday villa in Seignosse, a stone’s throw from the beaches and the school.', href: 'https://villadeladune-seignosse.fr', link: 'villadeladune-seignosse.fr' },
        { pin: 'Seignosse', h: 'Maison de la Dune', p: 'A charming holiday house in Seignosse, close to the spots and the centre.', href: 'https://maisondeladune-seignosse.fr', link: 'maisondeladune-seignosse.fr' },
        { pin: 'Labenne Océan', h: 'Board &amp; Breakfast', p: 'Anton welcomes you in his beautiful house with pool — rent it fully for up to 20 people, or surf-camp-style guest rooms.', href: 'https://boardnbreakfast.com', link: 'boardnbreakfast.com' },
        { pin: 'Seignosse', h: 'Campsites', p: 'Several campsites nearby, great in summer: Natureo, Les Marittimes and Les Oyats.', href: 'https://seignosse-tourisme.com', link: 'See the campsites' },
        { pin: 'Seignosse tourist office', h: 'More options', p: 'Find more accommodation and good tips through the Seignosse tourist office.', href: 'https://seignosse-tourisme.com', link: 'seignosse-tourisme.com' },
      ],
    },
    srilanka: {
      title: 'Sri Lanka surf camp — Midigama with Coco Surf School', desc: 'Join Coco Surf School on the south coast of Sri Lanka. Family house 100 m from Midigama beach — Lazy Left & Rams.', h1: 'Sri Lanka surf camp', crumb: 'Sri Lanka', bannerAlt: 'Sunset on the south coast of Sri Lanka', eyebrow: 'Surf camp',
      h1: 'Sri Lanka, with family',
      body: ['Your family stay on the beautiful south coast of Sri Lanka! We spend our winters with Budhika, Manori and Passandi, who have become our Sri Lankan family. Since Budhika lost his leg in a bus accident, the family relies completely on the income of the guesthouse; we help them develop the business. You can stay with them all year round!', 'The house is 100 m from the beach of Midigama — “Lazy Left” and “Rams” are your home spots. You’ll experience the real Sri Lanka: a home-made breakfast in the jungle garden, among squirrels, peacocks, monkeys and coconut palms. Manori is known for her cuisine — coconut rotti and egg hoppers for breakfast, rice &amp; curry for dinner. Ayurvedic massage on request.'],
      cta: 'Learn more about the camp', g1: 'Surfing a wave at Midigama, Sri Lanka', g2: 'Budhika, Manori and Passandi, the Sri Lankan family', g3: 'A peacock on the roof of the house in Sri Lanka',
    },
    contact: {
      title: 'Contact &amp; booking — Coco Surf School Hossegor &amp; Seignosse', desc: 'Book your surf lesson at Coco Surf School. Phone +33 6 47 45 42 65, email cocobosurfschool@gmail.com. 30% deposit.', h1: 'Contact', crumb: 'Contact',
      eyebrow: 'Contact', lead: 'The school welcomes you in Seignosse, Hossegor and Capbreton. Write to us to book your lesson or ask a question — we’ll be happy to reply.',
      phone: 'Phone', where: 'Where', deposit: 'A 30% deposit is requested on booking. Payment by bank transfer or cash.', fName: 'Name', fEmail: 'Email', fMsg: 'Message', fPlaceholder: 'Which lesson interests you? How many people? Which dates?', send: 'Send', faqTitle: 'Frequently asked questions',
      h1: 'Come surf with Coco Surf School',
      faq: [
        { q: 'Where do the surf lessons take place?', a: 'Coco Surf School is a mobile school between Hossegor and Seignosse: the best spot is chosen for your level and the conditions. In summer the school is based at Seignosse, Les Bourdaines.' },
        { q: 'How many people are there per lesson?', a: 'Quality over quantity: maximum 6 people per instructor (8 on request), for more coaching and faster progression.' },
        { q: 'Is the equipment included?', a: 'Yes, board and wetsuit are included in every lesson. Each lesson lasts 1h30.' },
        { q: 'How do I book and pay?', a: 'A 30% deposit is requested on booking. Payment is by bank transfer or cash.' },
        { q: 'Do I need to know how to surf already?', a: 'No. Annelies welcomes beginners as well as surfers who want to progress.' },
      ],
      jsonld: { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [
        { '@type': 'Question', name: 'Where do the surf lessons take place?', acceptedAnswer: { '@type': 'Answer', text: 'Coco Surf School is a mobile school between Hossegor and Seignosse: the best spot is chosen for your level and the conditions.' } },
        { '@type': 'Question', name: 'How many people are there per lesson?', acceptedAnswer: { '@type': 'Answer', text: 'Maximum 6 people per instructor (8 on request).' } },
        { '@type': 'Question', name: 'Is the equipment included?', acceptedAnswer: { '@type': 'Answer', text: 'Yes, board and wetsuit are included. Each lesson lasts 1h30.' } },
      ] },
    },
    hossegor: {
      title: 'Surf lessons in Hossegor — Coco Surf School | All levels', desc: 'Surf lessons in Hossegor with Coco Surf School. Small groups (max 6), board & wetsuit included, ISA-qualified coach.', h1: 'Surf lessons in Hossegor', crumb: 'Surf in Hossegor', ogImage: 'a29fce_94629df05b064d258b16bff511085d0d.jpg',
      eyebrow: 'Landes · France', h1html: 'Surf lessons in <em>Hossegor</em>', lead: 'Learn to surf in one of the most renowned surf towns in Europe. Small groups of 6 maximum, board and wetsuit included, with certified coaches.', cta1: 'Book a lesson', cta2: 'See rates', img: 'a29fce_94629df05b064d258b16bff511085d0d.jpg', imgAlt: 'Surfers on a Hossegor beach',
      body: '<p class="lead">Hossegor is the heart of surfing in the Landes, a reference for beach breaks in Europe. Coco Surf School is a mobile school between Hossegor and Seignosse: we choose the best spot for your level and the conditions of the day.</p><h2>Why learn in Hossegor?</h2><ul class="ticks"><li>Atlantic beach breaks suited to every level, from white water for beginners to punchier peaks.</li><li>A town built around surfing, ideal for a stay with your feet in the water.</li><li>Wide sandy beaches a stone’s throw from the ocean.</li></ul><h2>Lessons for every level</h2><p>Never surfed, or want to progress? Every session adapts to you. Lessons last 1h30, board and wetsuit included, in groups of 6 maximum (8 on request).</p><h2>Good to know</h2><p>The best spot — Hossegor or Seignosse — is chosen based on the tide, swell and wind. In summer the school is based at Seignosse, Les Bourdaines.</p>',
      aside: { h: 'Book in Hossegor', p: 'Small groups · all levels · gear included.', b1: 'Book a lesson', b2: 'WhatsApp' },
    },
    seignosse: {
      title: 'Surf lessons in Seignosse — Coco Surf School | Les Bourdaines', desc: 'Surf lessons in Seignosse (Les Bourdaines) with Coco Surf School. Gentle waves for beginners, small groups (max 6), gear included.', h1: 'Surf lessons in Seignosse', crumb: 'Surf in Seignosse', ogImage: 'a29fce_571dd78100a24c038429f1bfaf22b936.jpg',
      eyebrow: 'Landes · France', h1html: 'Surf lessons in <em>Seignosse</em>', lead: 'Our summer camp at Les Bourdaines: fun, gentle sandy beach breaks, perfect for learning. Small groups of 6 maximum, board and wetsuit included.', cta1: 'Book a lesson', cta2: 'See rates', img: 'a29fce_571dd78100a24c038429f1bfaf22b936.jpg', imgAlt: 'Les Bourdaines beach in Seignosse',
      body: '<p class="lead">Seignosse, just north of Hossegor, offers some of the most welcoming beaches in the Landes. In summer, Coco Surf School is based at Les Bourdaines — a wide sandy beach where the white water is ideal for your first waves.</p><h2>Why learn in Seignosse?</h2><ul class="ticks"><li>Sandy beach breaks at Les Bourdaines, gentle for beginners and intermediates.</li><li>A calmer, more natural setting than the town beaches.</li><li>The school’s summer camp: lessons easy to organise.</li></ul><h2>Lessons for every level</h2><p>From your first waves in the white water to your first take-offs on the green wave, every session adapts to you. Lessons last 1h30, board and wetsuit included, in small groups of 6 maximum. Larger groups are of course possible too.</p><h2>Good to know</h2><p>A mobile school between Seignosse, Hossegor and Capbreton: we choose the best spot for your level and the conditions of the day.</p>',
      aside: { h: 'Book in Seignosse', p: 'Small groups · all levels · gear included.', b1: 'Book a lesson', b2: 'WhatsApp' },
    },
    team: {
      title: 'Surf team building in the Landes — Coco Surf School', desc: 'Surf team building in Hossegor & Seignosse. A day out with colleagues: team spirit, stress relief and smiles guaranteed. Rates on request.', h1: 'Team building', crumb: 'Team building', ogImage: 'owner-team.png',
      eyebrow: 'Companies · Landes', h1html: 'Surf <em>team building</em>', lead: 'Go for a surf with your colleagues! Team spirit, stress relief and smiles all round — a sporty day in the ocean in Hossegor or Seignosse.', cta1: 'Request a quote', cta2: 'See rates', img: 'owner-team.png', imgAlt: 'Colleagues heading to the ocean with their boards',
      body: '<p class="lead">Fancy a different team activity in the Landes? Take your team surfing. A shared challenge in the ocean is one of the finest ways to build bonds — and everyone comes out of the water with a smile.</p><h2>Why surf as a team?</h2><ul class="ticks"><li><strong>Team spirit</strong> — a first shared experience where you cheer each other on.</li><li><strong>Stress relief</strong> — nothing clears the mind like the ocean and the fresh air.</li><li><strong>Accessible to all</strong> — no experience required, smiles guaranteed.</li></ul><h2>How it works</h2><p>Sessions are led by Annelies, an ISA-qualified coach, board and wetsuit included. We adapt the format to your group and choose the best beach between Hossegor and Seignosse. Rates on request.</p>',
      aside: { h: 'Organise your day', p: 'Tell us your group size and dates — a tailor-made quote.', b1: 'Request a quote', b2: 'WhatsApp' },
    },
    learn: {
      title: 'Learn to surf — Beginner lessons in Hossegor &amp; Seignosse', desc: 'Never surfed? Learn to surf with Coco Surf School. How your first lesson works, what’s included and how you progress in small groups of 6.', h1: 'Learn to surf', crumb: 'Learn to surf', ogImage: 'a29fce_4b942950b2834ef2ad4e3191df3d547a.jpg',
      eyebrow: 'For beginners', h1html: 'Learn to <em>surf</em>', lead: 'Never surfed? No worries. Here’s exactly how your first lesson works, what’s included and how quickly you progress.', cta1: 'Book your first lesson', cta2: 'See rates', img: 'a29fce_4b942950b2834ef2ad4e3191df3d547a.jpg', imgAlt: 'Students learning to surf in the white water',
      body: '<p class="lead">Surfing is one of the finest feelings there is — and you don’t need experience to start. At Coco Surf School you learn in a small group of 6 maximum, so the coach is with you from your very first wave.</p><h2>Your first lesson, step by step</h2><p>A lesson lasts 1h30 in the water — allow ±2h in total. We start on the beach with a warm-up and the basics — lying on the board, paddling, standing up. Then we head into the white water (the already-broken waves, near the shore), the safest and easiest place for your first rides. Most beginners get to their feet within the first few lessons.</p><h2>What’s included</h2><ul class="ticks"><li>Board and wetsuit — always included.</li><li>A certified coach, in a group of 6 maximum (8 on request).</li><li>The most beginner-friendly beach, chosen for the conditions of the day.</li></ul><h2>What to bring</h2><p>A swimsuit under the wetsuit, a towel, sunscreen and water. We take care of the rest.</p><h2>How quickly do you progress?</h2><p>Small groups = more coaching and faster progression. A <strong>little surf trip (3 lessons)</strong> or a <strong>5-day camp</strong> helps you really take off.</p>',
      aside: { h: 'Your first lesson', p: 'Small groups · all levels · gear included · 1h30.', b1: 'Book a lesson', b2: 'WhatsApp' },
    },
  },
};
